name = "MixtureDistributions"
uuid = "0f861121-9663-4ebe-adb7-33cfeeb12166"
authors = ["Michael-tehc <71926248+Michael-tehc@users.noreply.github.com>"]
version = "0.1.4"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25.112"
ForwardDiff = "1.1.0"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
Polynomials = "4.1.0"
QuadGK = "2.11.1"
Random = "1.11.0"
Revise = "3.9.0"
SpecialFunctions = "2.4.0"
StaticArrays = "1.9.15"
StatsBase = "0.34.6"
